/**
 * Solana IAO Factory Contract Service
 * Handles interaction with the IAO Factory program on Solana
 */

import {
  Connection,
  PublicKey,
  Transaction,
  TransactionInstruction,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import { TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID } from "@solana/spl-token";
import * as borsh from "borsh";

// IAO Factory Program ID (deployed on devnet)
export const IAO_FACTORY_PROGRAM_ID = new PublicKey(
  "FpCX6E1LxRph23NJgF9R8haRJscGPbbdhP2vd5Sn6jwA"
);

// USDC Mint on Solana Devnet
export const USDC_MINT_DEVNET = new PublicKey(
  "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
);

// Default RPC endpoint
const DEFAULT_RPC = "https://api.devnet.solana.com";

/**
 * Get Solana connection
 */
export function getConnection(rpcUrl?: string): Connection {
  return new Connection(rpcUrl || DEFAULT_RPC, "confirmed");
}

/**
 * Derive Factory State PDA
 */
export function getFactoryStatePDA(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("factory")],
    IAO_FACTORY_PROGRAM_ID
  );
}

/**
 * Derive IAO Token State PDA
 */
export function getTokenStatePDA(serverSlug: string): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("iao-token"), Buffer.from(serverSlug)],
    IAO_FACTORY_PROGRAM_ID
  );
}

/**
 * Derive Mint PDA
 */
export function getMintPDA(serverSlug: string): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("mint"), Buffer.from(serverSlug)],
    IAO_FACTORY_PROGRAM_ID
  );
}

/**
 * Derive Mint Authority PDA
 */
export function getMintAuthorityPDA(tokenStatePubkey: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("mint-authority"), tokenStatePubkey.toBuffer()],
    IAO_FACTORY_PROGRAM_ID
  );
}

/**
 * Anchor discriminator for instructions
 * Generated by hashing "global:<instruction_name>" with SHA256 and taking first 8 bytes
 */
async function getInstructionDiscriminatorAsync(name: string): Promise<Buffer> {
  const encoder = new TextEncoder();
  const data = encoder.encode(`global:${name}`);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  return Buffer.from(hashBuffer).slice(0, 8);
}

// Pre-computed discriminators (to avoid async in instruction building)
const DISCRIMINATORS: { [key: string]: number[] } = {
  // SHA256("global:initialize_factory")[:8]
  initialize_factory: [179, 64, 75, 250, 39, 254, 240, 178],
  // SHA256("global:create_token")[:8]
  create_token: [84, 52, 204, 228, 24, 140, 234, 75],
};

function getInstructionDiscriminator(name: string): Buffer {
  const disc = DISCRIMINATORS[name];
  if (!disc) {
    throw new Error(`Unknown instruction: ${name}`);
  }
  return Buffer.from(disc);
}

/**
 * Serialize string for Borsh (length-prefixed)
 */
function serializeString(str: string): Buffer {
  const strBuffer = Buffer.from(str, "utf-8");
  const lengthBuffer = Buffer.alloc(4);
  lengthBuffer.writeUInt32LE(strBuffer.length, 0);
  return Buffer.concat([lengthBuffer, strBuffer]);
}

/**
 * Serialize u64 for Borsh
 */
function serializeU64(value: bigint | number): Buffer {
  const buffer = Buffer.alloc(8);
  buffer.writeBigUInt64LE(BigInt(value), 0);
  return buffer;
}

/**
 * Create the Initialize Factory instruction
 */
export function createInitializeFactoryInstruction(
  admin: PublicKey,
  paymentTokenMint: PublicKey,
  paymentTokenPrice: bigint
): TransactionInstruction {
  const [factoryState, _factoryBump] = getFactoryStatePDA();

  const discriminator = getInstructionDiscriminator("initialize_factory");
  const priceBuffer = serializeU64(paymentTokenPrice);
  const data = Buffer.concat([discriminator, priceBuffer]);

  const keys = [
    { pubkey: factoryState, isSigner: false, isWritable: true },
    { pubkey: admin, isSigner: true, isWritable: true },
    { pubkey: paymentTokenMint, isSigner: false, isWritable: false },
    { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
  ];

  return new TransactionInstruction({
    keys,
    programId: IAO_FACTORY_PROGRAM_ID,
    data,
  });
}

/**
 * Create the Create Token instruction
 */
export function createCreateTokenInstruction(
  builder: PublicKey,
  serverSlug: string,
  name: string,
  symbol: string,
  uri: string = "",
  graduationThreshold: bigint = BigInt(0) // 0 = use default
): TransactionInstruction {
  const [factoryState, _factoryBump] = getFactoryStatePDA();
  const [tokenState, _tokenBump] = getTokenStatePDA(serverSlug);
  const [mint, _mintBump] = getMintPDA(serverSlug);
  const [mintAuthority, _mintAuthBump] = getMintAuthorityPDA(tokenState);

  // Build instruction data
  const discriminator = getInstructionDiscriminator("create_token");
  const serverSlugBuffer = serializeString(serverSlug);
  const nameBuffer = serializeString(name);
  const symbolBuffer = serializeString(symbol);
  const uriBuffer = serializeString(uri);
  const thresholdBuffer = serializeU64(graduationThreshold);

  const data = Buffer.concat([
    discriminator,
    serverSlugBuffer,
    nameBuffer,
    symbolBuffer,
    uriBuffer,
    thresholdBuffer,
  ]);

  const keys = [
    { pubkey: factoryState, isSigner: false, isWritable: true },
    { pubkey: tokenState, isSigner: false, isWritable: true },
    { pubkey: mint, isSigner: false, isWritable: true },
    { pubkey: mintAuthority, isSigner: false, isWritable: false },
    { pubkey: builder, isSigner: true, isWritable: true },
    { pubkey: TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
    { pubkey: ASSOCIATED_TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
    { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    { pubkey: SYSVAR_RENT_PUBKEY, isSigner: false, isWritable: false },
  ];

  return new TransactionInstruction({
    keys,
    programId: IAO_FACTORY_PROGRAM_ID,
    data,
  });
}

/**
 * Check if factory is initialized
 */
export async function isFactoryInitialized(connection: Connection): Promise<boolean> {
  const [factoryState] = getFactoryStatePDA();
  const accountInfo = await connection.getAccountInfo(factoryState);
  return accountInfo !== null;
}

/**
 * Get factory state data
 */
export async function getFactoryState(connection: Connection): Promise<any | null> {
  const [factoryState] = getFactoryStatePDA();
  const accountInfo = await connection.getAccountInfo(factoryState);

  if (!accountInfo) {
    return null;
  }

  // Skip 8-byte discriminator
  const data = accountInfo.data.slice(8);

  // Parse factory state (simplified - adjust based on actual struct)
  return {
    admin: new PublicKey(data.slice(0, 32)),
    automationWallet: new PublicKey(data.slice(32, 64)),
    paymentTokenMint: new PublicKey(data.slice(64, 96)),
    paymentTokenPrice: data.readBigUInt64LE(96),
    paymentTokenDecimals: data.readUInt8(104),
    totalTokensCreated: data.readBigUInt64LE(105),
    bump: data.readUInt8(113),
  };
}

/**
 * Get token state by server slug
 */
export async function getTokenState(
  connection: Connection,
  serverSlug: string
): Promise<any | null> {
  const [tokenState] = getTokenStatePDA(serverSlug);
  const accountInfo = await connection.getAccountInfo(tokenState);

  if (!accountInfo) {
    return null;
  }

  // Token state exists
  return {
    pubkey: tokenState,
    exists: true,
  };
}

/**
 * Create token on Solana
 * Returns the transaction to be signed by the wallet
 */
export async function createTokenTransaction(
  connection: Connection,
  builder: PublicKey,
  serverSlug: string,
  name: string,
  symbol: string,
  uri: string = ""
): Promise<{ transaction: Transaction; mintAddress: PublicKey; tokenStateAddress: PublicKey }> {
  // Check if factory is initialized
  const factoryInitialized = await isFactoryInitialized(connection);
  if (!factoryInitialized) {
    throw new Error("Factory not initialized. Please contact admin to initialize the factory.");
  }

  // Check if token already exists
  const existingToken = await getTokenState(connection, serverSlug);
  if (existingToken) {
    throw new Error(`Token for server slug "${serverSlug}" already exists on Solana.`);
  }

  // Get mint address for return value
  const [mintAddress] = getMintPDA(serverSlug);
  const [tokenStateAddress] = getTokenStatePDA(serverSlug);

  // Create instruction
  const instruction = createCreateTokenInstruction(
    builder,
    serverSlug,
    name,
    symbol,
    uri
  );

  // Build transaction
  const transaction = new Transaction();
  transaction.add(instruction);

  // Get recent blockhash
  const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash();
  transaction.recentBlockhash = blockhash;
  transaction.lastValidBlockHeight = lastValidBlockHeight;
  transaction.feePayer = builder;

  return { transaction, mintAddress, tokenStateAddress };
}

/**
 * Initialize factory (admin only, one-time)
 */
export async function initializeFactoryTransaction(
  connection: Connection,
  admin: PublicKey,
  paymentTokenMint: PublicKey = USDC_MINT_DEVNET,
  paymentTokenPrice: bigint = BigInt(1000000) // $1.00 in 6 decimals
): Promise<Transaction> {
  // Check if already initialized
  const factoryInitialized = await isFactoryInitialized(connection);
  if (factoryInitialized) {
    throw new Error("Factory is already initialized.");
  }

  // Create instruction
  const instruction = createInitializeFactoryInstruction(
    admin,
    paymentTokenMint,
    paymentTokenPrice
  );

  // Build transaction
  const transaction = new Transaction();
  transaction.add(instruction);

  // Get recent blockhash
  const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash();
  transaction.recentBlockhash = blockhash;
  transaction.lastValidBlockHeight = lastValidBlockHeight;
  transaction.feePayer = admin;

  return transaction;
}
